### ISSUE TITLE
Publish binaries for release

### ISSUE THREAD

**Issue by Stupremee** [RDambrosio016/RSLint#18]
Since most people that will use RSLint are going to be JavaScript / TypeScript developers, many of them will not have Rust installed. So it would be nice to add workflows to publish binaries for multiple platforms in every release and upload them to the specific GitHub release as an asset.

**Comment by RDambrosio016** [comment]
Yeah that is planned, i just have not gotten around to setting up CI to do that, and i don't really expect many people to use it as a prebuilt binary at this point since its got a lot of bugs and is still early in development.
