### ISSUE TITLE
Curly brackets where parameters should be should be parsed as block statements not object expressions

### ISSUE THREAD

**Issue by RDambrosio016** [RDambrosio016/RSLint#24]
For example:

```js
function {}
```
and 
```js
class foo {
set {}
}
```
in both of these examples `{}` should not be parsed as an object pattern for the parameters, it should be parsed as a block statement since object patterns in parameters are exceedingly rare and it is much better to assume the user forgot the parameters. This can probably be done by keeping some state boolean which is switched on if formal_parameters does not see a `(` and sees a `{`, then primary_expr simply checks that boolean

**Comment by RDambrosio016** [comment]
Hmm this is probably more E-medium, i am a bit biased when it comes to parser difficulty 😄

**Comment by Stupremee** [comment]
I will actually fix this in my next PR while fixing some other test262 bugs :+1:
