### ISSUE TITLE
Shebangs should be parsed correctly

### ISSUE THREAD

**Issue by RDambrosio016** [RDambrosio016/RSLint#26]
Shebang support is not a thing, which is incorrect. However, supporting shebangs is pretty easy, a `SHEBANG` token kind already exists, so all that needs to be done is add a handler for it in the lexer, the logic is already there in `Lexer::strip_shebang`, so just add something in the lookup table which checks `#`, then in the match simply match for the dispatch then peek for `!`, you must also check if the current position is `0`.  Then for the parser:
- Add a field to Script and Module in xtask/src/ast.rs:
```diff
struct Script {
+    T![shebang],
     items: [Stmt],
  }

struct Module {
+    T![shebang],
     items: [ModuleItem],
}
```
- regenerate the definitions with `cargo xtask syntax`
- add a simple `p.eat(T![shebang]);` after `let m = p.start();` in rslint_parser/src/syntax/program.rs in `script` and `module`
- log the change in the rslint_lexer and rslint_parser changelogs, as well as add lexer tests for it

**Comment by magurotuna** [comment]
Could I work on it?

**Comment by RDambrosio016** [comment]
Sure! go ahead
