### ISSUE TITLE
Test262 integration

### ISSUE THREAD

**Issue by Stupremee** [RDambrosio016/RSLint#27]
[Test262](https://github.com/tc39/test262) is the official test suite for validating ECMAScript compatibility.
To confirm that `rslint_parser` can parse the whole (or most of) the ECMA-262 specification.

The integration of test262 will probably be a bit tricky because there is much work required to set it up to a custom
parser. I would suggest using a similar approach like [boa](https://github.com/boa-dev/boa),
to have an extra workspace member (e.g. `rslint_tester`) that will run the whole test suite against `rslint_parser`
and then report how much of the specification can be parsed and what failed to parse correctly.

This could also be run in CI workflow, to see a regression of the passing and failing tests.

**Comment by RDambrosio016** [comment]
Yeah im torn between making it a test in rslint_parser and making it a full member, although i think making it a test would be better. As for running them we simply just need serde_yaml and some rayon to parallelize the jobs.

**Comment by RDambrosio016** [comment]
Closing in favor of #28
