### ISSUE TITLE
Consider switching from codespan-reporting to annotate-snippets

### ISSUE THREAD

**Issue by RDambrosio016** [RDambrosio016/RSLint#29]
# Motivation 

Codespan-reporting is amazing in terms of its files interface, however, it has no middle-level representation, and this has proven to be very very limiting. RSLint could greatly greatly benefit from things such as multiline suggestions like rustc. I think for the future it would be beneficial to make an `rslint_errors` crate which uses annotate-snippets as a backend for rendering, or maybe fork annotate-snippets. 

# Switching 

The change would greatly affect rslint_lexer because it relies on codespan's diagnostic builder, this should be easy to switch out though. Moreover, the file walker would not have to have codespan specific files stuff, it would only need a way of getting the source code for annotate-snippets. Perhaps we should make a Files trait in rslint_errors. Then it should be simple from there. However, diagnostic builders may not work well since rslint_errors cannot rely on rslint_parser since it would be a cyclic dep, therefore we cannot make a Span trait like rslint_core. So we need to either give up the Span trait or make a wrapper of the builder in rslint_core.

**Comment by Stupremee** [comment]
Can you name more benefits that make annotate-snippets better than codespan (except multiline-suggestions)?

**Comment by Stupremee** [comment]
I came up with a simple API design that is similair to codespan-reporting but adjusted to work with annotate-snippets
```rust
// not sure if we want to change the name to `Snippet` or stay with `Diagnostic`
Snippet::new(file_id)
    .title(Annotation::note("SyntaxError", "expected `,`, found `;`"))
    .annotate(AnnotatioType::Error, span, "")
    .annotate_help(span, "remove this `;`")
    .footer(Footer::help("remove this `;`"))
```

To display the errors we could take a similar approach as codespan-reporting and have an extra method (`emit`)
that will take a `impl Files` and `Vec<Snippet>` and will display them.

**Comment by RDambrosio016** [comment]
I would rather not keep the Snippet name, i dont really like it, i think diagnostic is better and most of rslint uses the word diagnostic. Moreover, id like to keep the diagnostic builder interface for the most part, also, id like to take some ideas from rustc_errors. I think this would be better:

```rust
Diagnostic::new(file_id, "some-code", "some error name here")
  .primary(span, "oh no")
  .secondary(span, "oh wow")
  .suggestion(Applicability::Always, "isNaN(foo)")
```

I think for the struct we can take some ideas from rustc_errors, notes are sub-diagnostics, suggestions are a vector of suggestions, etc. suggestions would use a diff to label any insertions, and we can also have other kinds of sub-diagnostics. Annotate-snippets' IR makes it easy for us to define our own diagnostic features

**Comment by Stupremee** [comment]
So you don't want to use the different annotation types for the labels / slices that can be used in annotate-snippets?
I think they can be quite useful.

**Comment by RDambrosio016** [comment]
i would rather stick with primary/secondary and then just add info, i dont think theres a difference between info, note, and help

**Comment by Stupremee** [comment]
I will officially work on this now
