### ISSUE TITLE
Q*A request

### ISSUE THREAD

**Issue by brucou** [RDambrosio016/RSLint#41]
Hi,

Would you be interested in a Q&A on RSLint? I am a news editor for infoq.com, which focuses on bringing the latest innovation to a core audience of tech leads, software architects and senior developers. You can see an example of Q&A here: https://www.infoq.com/news/2019/07/doom3-web-assembly-port/

Let me know if that sounds of interest to you. If that is the case, we can continue the conversation through regular email.

Congratulations in any case for pushing this through. I know the amount of motivation and effort it takes to brings an open-source project forward.

Kind regards,

**Comment by RDambrosio016** [comment]
Yeah sure! feel free to email me

**Comment by RDambrosio016** [comment]
Ill go ahead and close this since we can continue this through email 👍

**Comment by Stupremee** [comment]
Uhh, pls send me the finished post
