### ISSUE TITLE
.eslintrc config compatibility

### ISSUE THREAD

**Issue by Stupremee** [RDambrosio016/RSLint#44]
First: this is totally not ready to implement and should be delayed until we support most of (or even all) the rules eslint supports.

For a simple switch from eslint to RSLint, it would be awesome to be able to use
an `.eslintrc.json` (or others) for RSLint configuration. This *should* be really easy to implement I think.
Imo this should be provided using an extra argument but I'm open for other suggestions

### Alternatives

We could provide a tool to convert an eslint config file, to an rslint one. This should be pretty easy too (at least for json, yaml).

**Comment by RDambrosio016** [comment]
I would rather not do that, i don't want the tool to be constrained by eslint's config, and rslint's config is quite different. My plan is to have tools in the cli which allow you to automatically switch eslint items to rslint or to guide you through doing it.

**Comment by Stupremee** [comment]
thats fine too

**Comment by RDambrosio016** [comment]
Off the top of my head:
- rslint has the concept of groups, eslint does not
- rslint does not require parser config
- rslint will have an errors field to configure error output
- rslint uses `rules.warnings` and `rules.errors`, while eslint just has a rules object and their level is configured through the key

**Comment by RDambrosio016** [comment]
I realize a big wall in getting more people to use rslint will be switching from eslint, so offering tools to make it easy will be vital. Things like directives work differently in rslint (statement scoped vs line scoped), so interop is kind of limiting.

**Comment by Stupremee** [comment]
Yea, but an interactive CLI conversion tool sounds like a nice idea.

**Comment by RDambrosio016** [comment]
Yeah which is what i plan on doing, dialoguer and rustyline should make this extremely simple

**Comment by RDambrosio016** [comment]
I'll go ahead and close this as its resolved, rslint will provide conversion tools but will not do interop with eslint.
