### ISSUE TITLE
Parser do not support field property

### ISSUE THREAD

**Issue by rrandom** [RDambrosio016/RSLint#55]
**I tried this code**:

```js
class ClassWithInstanceField {
  instanceField = 'instance field'
}

class ClassWithStaticField {   
  static staticField = 'static field' 
}
```

**I expected this to happen**: *Parse without errors*

**Instead this happened:**: *error[SyntaxError]: expected `'('` but instead found `=`*

### Meta 
`rslint -V`:  rslint 0.1.2

If building from source:
`rustc --version --verbose`:
```
<version>
```

**Additional context**
 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields

**Comment by RDambrosio016** [comment]
Static fields are a TC39 stage 3 proposal, they arent part of the language yet, and we do not support proposals yet
