### ISSUE TITLE
Panic on uppercase numeric literals

### ISSUE THREAD

**Issue by Stupremee** [RDambrosio016/RSLint#7]
**I tried this code**:

```js
0XFF
```

**I expected this to happen**: `0XFF` should be parsed as `255` / `0xFF`

**Instead this happened:**: RSLint panicked

### Meta 
If building from source:
`rustc --version --verbose`:
```
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0
```

**Additional context**
I would like to fix the problem

**Comment by Stupremee** [comment]
I noticed that theres a "Fixes `rslint_parser::numbers::parse_js_num`" in #4 .
I can also fix whatever you want to be fixed in `parse_js_num` and add tests

**Comment by RDambrosio016** [comment]
Could you please post the panic message? it should be stripping off the prefix and relying on the stdlib's implementation for parsing hex

**Comment by RDambrosio016** [comment]
Ah it seems i forgot to account for `0X`, `0B` and `0O` in parse_js_num, ill fix it right now, thanks for finding a bug 👍

**Comment by Stupremee** [comment]
Yes that's the normal behavior, but "0X" is not matched and stripped off
